package main

import (
	"crypto/rand"
	_ "embed"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

//go:embed templates/schema.json
var starterSchema []byte

var initCmd = &cobra.Command{
	Use:   "init [name]",
	Short: "Initialize a new Appximo project",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		blueprint, _ := cmd.Flags().GetString("blueprint")

		schemaBytes, err := resolveSchema(blueprint)
		if err != nil {
			return err
		}

		if err := os.MkdirAll(name, 0755); err != nil {
			return fmt.Errorf("create directory %q: %w", name, err)
		}

		schemaPath := filepath.Join(name, "schema.json")
		if err := os.WriteFile(schemaPath, schemaBytes, 0644); err != nil {
			return fmt.Errorf("write schema.json: %w", err)
		}

		// PUBLIC-SURFACE-S1 Part A: init emits a COMPLETE, compilable project —
		// a main.go with Config.Static wired (the flagship one-binary shape) and
		// a web/ placeholder the embed needs — not a go.mod orphan the second
		// field report found ("no main.go — the project Go code would need").
		goMod := fmt.Sprintf("module %s\n\ngo 1.25.0\n", name)
		if err := os.WriteFile(filepath.Join(name, "go.mod"), []byte(goMod), 0644); err != nil {
			return fmt.Errorf("write go.mod: %w", err)
		}
		if err := os.WriteFile(filepath.Join(name, "main.go"), []byte(initMainGo(name)), 0644); err != nil {
			return fmt.Errorf("write main.go: %w", err)
		}
		if err := os.MkdirAll(filepath.Join(name, "web"), 0755); err != nil {
			return fmt.Errorf("create web/: %w", err)
		}
		if err := os.WriteFile(filepath.Join(name, "web", "index.html"), []byte(initIndexHTML(name)), 0644); err != nil {
			return fmt.Errorf("write web/index.html: %w", err)
		}
		gitignore := ".env\n/" + name + "\n"
		if err := os.WriteFile(filepath.Join(name, ".gitignore"), []byte(gitignore), 0644); err != nil {
			return fmt.Errorf("write .gitignore: %w", err)
		}

		// F2 (FIELD-FEEDBACK-S1): --env writes a ready .env — generated
		// secrets, correct sizes, no BOM — so the first boot is one step. The
		// engine loads it automatically (the real environment wins).
		if withEnv, _ := cmd.Flags().GetBool("env"); withEnv {
			jwt, err := randHexSecret(32)
			if err != nil {
				return fmt.Errorf("generate JWT_SECRET: %w", err)
			}
			adminKey, err := randHexSecret(16)
			if err != nil {
				return fmt.Errorf("generate ADMIN_KEY: %w", err)
			}
			env := "# Generated by `appximo init --env` — loaded automatically by the CLI\n" +
				"# (KEY=value per line; a variable already set in the environment wins).\n" +
				"# Fill in DATABASE_URL, then: appximo serve --schema schema.json\n" +
				"DATABASE_URL=postgres://user:password@localhost:5432/" + name + "\n" +
				"JWT_SECRET=" + jwt + "\n" +
				"ADMIN_KEY=" + adminKey + "\n"
			if err := os.WriteFile(filepath.Join(name, ".env"), []byte(env), 0o600); err != nil {
				return fmt.Errorf("write .env: %w", err)
			}
			fmt.Printf("  → .env written (0600): JWT_SECRET + ADMIN_KEY generated; edit DATABASE_URL\n")
		}

		if blueprint != "" {
			fmt.Printf("Project %q initialized with blueprint %q.\n", name, blueprint)
		} else {
			fmt.Printf("Project %q initialized.\n", name)
		}
		fmt.Printf("  schema.json    your API (edit it; appximo validate schema.json)\n")
		fmt.Printf("  main.go        the one-binary app: engine + your frontend (web/ is embedded)\n")
		fmt.Printf("  web/           replace with your frontend's build output (index.html placeholder inside)\n")
		fmt.Println("  → Build & run:")
		fmt.Printf("  →   cd %s && go mod tidy && go build\n", name)
		fmt.Printf("  →   ./%s serve   (needs DATABASE_URL, JWT_SECRET, ADMIN_KEY — a ./.env is loaded automatically%s)\n", name, initEnvHint(cmd))
		fmt.Println("  → No Go needed? The engine binary serves a frontend too: appximo serve --static ./dist --spa")
		return nil
	},
}

// initMainGo renders the generated project's main.go: the canonical ADR-023 +
// Config.Static pairing (ParseServeArgs contract, go:embed'd web/, SPA mount at
// "/"). It must COMPILE AND RUN as generated — pinned by the init integration
// test, which builds the generated project against this working tree.
func initMainGo(name string) string {
	return fmt.Sprintf(`package main

// Generated by 'appximo init' — a complete Appximo app in one binary: the
// schema-driven API plus your frontend, served from the same origin (no CORS).
//
//	go mod tidy && go build     # first build fetches the framework
//	./%[1]s serve               # needs DATABASE_URL, JWT_SECRET, ADMIN_KEY
//	                            # (a ./.env is loaded automatically)
//
// Replace web/ with your frontend's build output; the embed compiles it into
// the binary. Custom Go endpoints: app.Register(appximo.Route{…}) before
// Start — 'appximo backend-spec' prints the whole contract.

import (
	"embed"
	"fmt"
	"io/fs"
	"os"

	"github.com/appximo/appximo"
)

//go:embed all:web
var frontend embed.FS

// Injected at release time: go build -ldflags "-X main.version=v1.0.0 -X main.revision=$(git rev-parse --short HEAD)"
var version, revision = "dev", "unknown"

func main() {
	args := appximo.ParseServeArgs(%[1]q, version, revision, appximo.ServeArgs{})

	web, err := fs.Sub(frontend, "web")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	app, err := appximo.New(appximo.Config{
		SchemaPath:  args.SchemaPath,
		Port:        args.Port,
		ControlPort: args.ControlPort,
		Version:     version,
		// The one-binary shape: your frontend at "/", the API at /api, docs at
		// /docs — same origin, engine-owned paths never shadowed.
		Static: []appximo.StaticMount{{Path: "/", FS: web, SPA: true}},
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := app.Start(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`, name)
}

// initIndexHTML is the web/ placeholder: real enough that the freshly-built
// binary shows a working page, explicit that it is meant to be replaced.
func initIndexHTML(name string) string {
	return fmt.Sprintf(`<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>%[1]s</title></head>
<body style="font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto; padding: 0 1rem">
  <h1>%[1]s is running</h1>
  <p>This page is <code>web/index.html</code>, embedded in your binary. Replace
  the <code>web/</code> directory with your frontend's build output and rebuild.</p>
  <p>The API this binary serves: <a href="/docs">/docs</a> · <code>/api/…</code> · <a href="/openapi.json">/openapi.json</a></p>
</body>
</html>
`, name)
}

// initEnvHint tells the user whether --env already wrote the file.
func initEnvHint(cmd *cobra.Command) string {
	if withEnv, _ := cmd.Flags().GetBool("env"); withEnv {
		return "; .env is already written — edit DATABASE_URL"
	}
	return ""
}

// resolveSchema returns the bytes to write as schema.json: blueprint file if a
// name is given, otherwise the embedded starter template.
func resolveSchema(blueprint string) ([]byte, error) {
	if blueprint == "" {
		return starterSchema, nil
	}
	path := filepath.Join("blueprints", blueprint+".json")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("blueprint %q not found at %s\n  Run 'appximo blueprints list' to see available blueprints", blueprint, path)
		}
		return nil, fmt.Errorf("read blueprint %q: %w", blueprint, err)
	}
	return data, nil
}

func init() {
	initCmd.Flags().String("blueprint", "", "blueprint to use (e.g. fintech, ecommerce, crm)")
	initCmd.Flags().Bool("env", false, "also write a ready .env (generated JWT_SECRET + ADMIN_KEY; DATABASE_URL template)")
	rootCmd.AddCommand(initCmd)
}

// randHexSecret returns n random bytes hex-encoded (2n characters).
func randHexSecret(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}
