package main

import (
	"crypto/rand"
	_ "embed"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

//go:embed templates/schema.json
var starterSchema []byte

var initCmd = &cobra.Command{
	Use:   "init [name]",
	Short: "Initialize a new Appximo project",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		blueprint, _ := cmd.Flags().GetString("blueprint")

		schemaBytes, err := resolveSchema(blueprint)
		if err != nil {
			return err
		}

		if err := os.MkdirAll(name, 0755); err != nil {
			return fmt.Errorf("create directory %q: %w", name, err)
		}

		schemaPath := filepath.Join(name, "schema.json")
		if err := os.WriteFile(schemaPath, schemaBytes, 0644); err != nil {
			return fmt.Errorf("write schema.json: %w", err)
		}

		goMod := fmt.Sprintf("module %s\n\ngo 1.22\n", name)
		if err := os.WriteFile(filepath.Join(name, "go.mod"), []byte(goMod), 0644); err != nil {
			return fmt.Errorf("write go.mod: %w", err)
		}

		// F2 (FIELD-FEEDBACK-S1): --env writes a ready .env — generated
		// secrets, correct sizes, no BOM — so the first boot is one step. The
		// engine loads it automatically (the real environment wins).
		if withEnv, _ := cmd.Flags().GetBool("env"); withEnv {
			jwt, err := randHexSecret(32)
			if err != nil {
				return fmt.Errorf("generate JWT_SECRET: %w", err)
			}
			adminKey, err := randHexSecret(16)
			if err != nil {
				return fmt.Errorf("generate ADMIN_KEY: %w", err)
			}
			env := "# Generated by `appximo init --env` — loaded automatically by the CLI\n" +
				"# (KEY=value per line; a variable already set in the environment wins).\n" +
				"# Fill in DATABASE_URL, then: appximo serve --schema schema.json\n" +
				"DATABASE_URL=postgres://user:password@localhost:5432/" + name + "\n" +
				"JWT_SECRET=" + jwt + "\n" +
				"ADMIN_KEY=" + adminKey + "\n"
			if err := os.WriteFile(filepath.Join(name, ".env"), []byte(env), 0o600); err != nil {
				return fmt.Errorf("write .env: %w", err)
			}
			fmt.Printf("  → .env written (0600): JWT_SECRET + ADMIN_KEY generated; edit DATABASE_URL\n")
		}

		if blueprint != "" {
			fmt.Printf("Project %q initialized with blueprint %q.\n", name, blueprint)
		} else {
			fmt.Printf("Project %q initialized.\n", name)
		}
		fmt.Println("  → Edit schema.json and run:")
		fmt.Println("  → appximo validate schema.json")
		fmt.Println("  → appximo generate schema.json")
		return nil
	},
}

// resolveSchema returns the bytes to write as schema.json: blueprint file if a
// name is given, otherwise the embedded starter template.
func resolveSchema(blueprint string) ([]byte, error) {
	if blueprint == "" {
		return starterSchema, nil
	}
	path := filepath.Join("blueprints", blueprint+".json")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("blueprint %q not found at %s\n  Run 'appximo blueprints list' to see available blueprints", blueprint, path)
		}
		return nil, fmt.Errorf("read blueprint %q: %w", blueprint, err)
	}
	return data, nil
}

func init() {
	initCmd.Flags().String("blueprint", "", "blueprint to use (e.g. fintech, ecommerce, crm)")
	initCmd.Flags().Bool("env", false, "also write a ready .env (generated JWT_SECRET + ADMIN_KEY; DATABASE_URL template)")
	rootCmd.AddCommand(initCmd)
}

// randHexSecret returns n random bytes hex-encoded (2n characters).
func randHexSecret(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}
