package schemadiff_test

// Minimal DDL renderer for the diff tests. It turns a typed operation Plan into
// SQL just well enough to APPLY it against a real Postgres and verify convergence
// — it is NOT the engine's renderer (safe DDL with lock_timeout, expand/contract,
// CONCURRENTLY, etc. is a later session). It covers exactly the operations the
// tests exercise. Identifiers are rendered unqualified and quoted; apply() runs
// every statement on a connection whose search_path is the ephemeral test schema.

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"

	sd "github.com/miguelangel/appitools/pkg/schemadiff"
)

func q(name string) string { return `"` + name + `"` }

func qcols(cols []string) string {
	out := make([]string, len(cols))
	for i, c := range cols {
		out[i] = q(c)
	}
	return strings.Join(out, ", ")
}

func serialFor(b sd.BaseType) string {
	switch b {
	case sd.BaseBigint:
		return "bigserial"
	case sd.BaseSmallint:
		return "smallserial"
	default:
		return "serial"
	}
}

func renderColumnDef(c *sd.Column) string {
	if c.Identity != nil && c.Identity.Generated == "serial" {
		return q(c.Name) + " " + serialFor(c.Type.Base)
	}
	def := q(c.Name) + " " + c.Type.String()
	if c.Identity != nil {
		switch c.Identity.Generated {
		case "always":
			return def + " GENERATED ALWAYS AS IDENTITY"
		case "by_default":
			return def + " GENERATED BY DEFAULT AS IDENTITY"
		}
	}
	if c.NotNull {
		def += " NOT NULL"
	}
	if c.Default != nil {
		def += " DEFAULT " + c.Default.Raw
	}
	return def
}

func renderCreateTable(t *sd.Table) string {
	var cols []string
	for _, name := range t.ColumnOrder {
		cols = append(cols, renderColumnDef(t.Columns[name]))
	}
	if t.PK != nil {
		cols = append(cols, "PRIMARY KEY ("+qcols(t.PK.Columns)+")")
	}
	return "CREATE TABLE " + q(t.Name) + " (\n  " + strings.Join(cols, ",\n  ") + "\n)"
}

func renderAlterColumn(o sd.AlterColumn) []string {
	var stmts []string
	tbl, col := q(o.Table), q(o.To.Name)
	if o.TypeChanged() {
		ty := o.To.Type.String()
		stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s USING %s::%s", tbl, col, ty, col, ty))
	}
	if o.NullabilityAdded() {
		stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL", tbl, col))
	}
	if o.NullabilityDropped() {
		stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL", tbl, col))
	}
	if o.DefaultChanged() {
		if o.To.Default == nil {
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT", tbl, col))
		} else {
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s", tbl, col, o.To.Default.Raw))
		}
	}
	return stmts
}

func renderAddFK(o sd.AddForeignKey) string {
	s := fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
		q(o.Table), q(o.FK.Symbol), qcols(o.FK.Columns), q(o.FK.RefTable), qcols(o.FK.RefColumns))
	if o.FK.OnDelete != sd.NoAction {
		s += " ON DELETE " + o.FK.OnDelete.String()
	}
	if o.FK.OnUpdate != sd.NoAction {
		s += " ON UPDATE " + o.FK.OnUpdate.String()
	}
	return s
}

func renderAddIndex(o sd.AddIndex) string {
	u := ""
	if o.Index.Unique {
		u = "UNIQUE "
	}
	s := "CREATE " + u + "INDEX " + q(o.Index.Name) + " ON " + q(o.Table)
	if o.Index.Method != "" && o.Index.Method != "btree" {
		s += " USING " + o.Index.Method
	}
	s += " (" + qcols(o.Index.Columns) + ")"
	if o.Index.Predicate != "" {
		s += " WHERE " + o.Index.Predicate
	}
	return s
}

// renderOp returns the DDL statement(s) for one operation.
func renderOp(op sd.Operation) []string {
	switch o := op.(type) {
	case sd.CreateTable:
		return []string{renderCreateTable(o.Table)}
	case sd.DropTable:
		return []string{"DROP TABLE " + q(o.Table.Name)}
	case sd.RenameTable:
		return []string{"ALTER TABLE " + q(o.From) + " RENAME TO " + q(o.To)}
	case sd.AddColumn:
		return []string{"ALTER TABLE " + q(o.Table) + " ADD COLUMN " + renderColumnDef(o.Column)}
	case sd.DropColumn:
		return []string{"ALTER TABLE " + q(o.Table) + " DROP COLUMN " + q(o.Column.Name)}
	case sd.AlterColumn:
		return renderAlterColumn(o)
	case sd.RenameColumn:
		return []string{"ALTER TABLE " + q(o.Table) + " RENAME COLUMN " + q(o.From) + " TO " + q(o.To)}
	case sd.AddPrimaryKey:
		return []string{"ALTER TABLE " + q(o.Table) + " ADD CONSTRAINT " + q(o.PK.Name) + " PRIMARY KEY (" + qcols(o.PK.Columns) + ")"}
	case sd.DropPrimaryKey:
		return []string{"ALTER TABLE " + q(o.Table) + " DROP CONSTRAINT " + q(o.PK.Name)}
	case sd.AddForeignKey:
		return []string{renderAddFK(o)}
	case sd.DropForeignKey:
		return []string{"ALTER TABLE " + q(o.Table) + " DROP CONSTRAINT " + q(o.FK.Symbol)}
	case sd.AddUnique:
		return []string{"ALTER TABLE " + q(o.Table) + " ADD CONSTRAINT " + q(o.Unique.Symbol) + " UNIQUE (" + qcols(o.Unique.Columns) + ")"}
	case sd.DropUnique:
		return []string{"ALTER TABLE " + q(o.Table) + " DROP CONSTRAINT " + q(o.Unique.Symbol)}
	case sd.AddCheck:
		return []string{"ALTER TABLE " + q(o.Table) + " ADD CONSTRAINT " + q(o.Check.Symbol) + " CHECK " + o.Check.Expression}
	case sd.DropCheck:
		return []string{"ALTER TABLE " + q(o.Table) + " DROP CONSTRAINT " + q(o.Check.Symbol)}
	case sd.AddIndex:
		return []string{renderAddIndex(o)}
	case sd.DropIndex:
		return []string{"DROP INDEX " + q(o.Index.Name)}
	}
	panic(fmt.Sprintf("renderOp: unhandled operation %T", op))
}

// apply runs every operation's DDL on one connection whose search_path is the
// ephemeral schema, so the unqualified identifiers resolve there.
func apply(t *testing.T, pool *pgxpool.Pool, schema string, plan *sd.Plan) {
	t.Helper()
	ctx := context.Background()
	conn, err := pool.Acquire(ctx)
	if err != nil {
		t.Fatalf("acquire conn: %v", err)
	}
	defer conn.Release()
	if _, err := conn.Exec(ctx, "SET search_path TO "+q(schema)); err != nil {
		t.Fatalf("set search_path: %v", err)
	}
	for _, op := range plan.Ops {
		for _, stmt := range renderOp(op) {
			if _, err := conn.Exec(ctx, stmt); err != nil {
				t.Fatalf("apply [%s]\n  stmt: %s\n  err:  %v", op, stmt, err)
			}
		}
	}
}

func introspectSchema(t *testing.T, pool *pgxpool.Pool, schema string) *sd.Schema {
	t.Helper()
	s, err := sd.Introspect(context.Background(), pool, schema)
	if err != nil {
		t.Fatalf("introspect %s: %v", schema, err)
	}
	return s
}
