package codegen

import (
	"sort"
	"strings"

	"github.com/miguelangel/appitools/pkg/schema"
	"gopkg.in/yaml.v3"
)

type openAPISpec struct {
	OpenAPI    string           `yaml:"openapi"`
	Info       map[string]any   `yaml:"info"`
	Servers    []map[string]any `yaml:"servers,omitempty"`
	Security   []map[string]any `yaml:"security"`
	Paths      map[string]any   `yaml:"paths"`
	Components map[string]any   `yaml:"components"`
}

// GenerateOpenAPI produces an OpenAPI 3.0.3 YAML document from an APISchema.
// baseURL is set as the server URL (defaults to "/" when empty).
func GenerateOpenAPI(s *schema.APISchema, baseURL string) ([]byte, error) {
	if baseURL == "" {
		baseURL = "/"
	}
	spec := openAPISpec{
		OpenAPI: "3.0.3",
		Info: map[string]any{
			"title":       s.Name,
			"version":     s.Version,
			"description": "Generated by Appitools — https://github.com/miguelangel/appitools",
		},
		Servers:    []map[string]any{{"url": baseURL, "description": "API server"}},
		Security:   []map[string]any{{"bearerAuth": []string{}}},
		Paths:      buildOAPaths(s),
		Components: buildOAComponents(s),
	}
	return yaml.Marshal(spec)
}

// ── paths ─────────────────────────────────────────────────────────────────────

func buildOAPaths(s *schema.APISchema) map[string]any {
	paths := map[string]any{}
	for _, name := range sortedResourceKeys(s) {
		res := s.Resources[name]
		title := toPascalCase(name)
		paths["/api/"+name] = map[string]any{
			"get":  oaListOp(name, title, &res),
			"post": oaCreateOp(name, title),
		}
		paths["/api/"+name+"/{id}"] = map[string]any{
			"get":    oaGetOp(name, title),
			"put":    oaReplaceOp(name, title),
			"patch":  oaUpdateOp(name, title),
			"delete": oaDeleteOp(name, title),
		}
		// subresource paths
		for _, fname := range sortedFieldKeys(&res) {
			fd := res.Fields[fname]
			if fd.Relation == "" {
				continue
			}
			relName := strings.TrimSuffix(fname, "_id")
			relTitle := toPascalCase(fd.Relation)
			paths["/api/"+name+"/{id}/"+relName] = map[string]any{
				"get": oaSubresourceOp(name, title, relName, relTitle, fd.Relation, fname),
			}
		}
	}
	return paths
}

func oaListOp(name, title string, res *schema.ResourceSchema) map[string]any {
	params := []any{
		oaQueryParam("page", map[string]any{
			"type":    "integer",
			"default": 1,
			"minimum": 1,
		}),
		oaQueryParam("per_page", map[string]any{
			"type":    "integer",
			"default": 20,
			"minimum": 1,
			"maximum": 100,
		}),
		oaQueryParamDesc("sort", map[string]any{"type": "string", "enum": oaSortEnum(res)},
			"Field to sort by (legacy). Prefer order[field]=asc|desc"),
		oaQueryParamDesc("order", map[string]any{"type": "string", "enum": []string{"asc", "desc"}, "default": "asc"},
			"Sort direction for the sort field (legacy)"),
		oaQueryParamDesc("search", map[string]any{"type": "string"},
			"Full-text search across all string fields (ILIKE)"),
	}

	// order[field] params
	for _, fname := range sortedFieldKeys(res) {
		params = append(params, oaQueryParamDesc(
			"order["+fname+"]",
			map[string]any{"type": "string", "enum": []string{"asc", "desc"}},
			"Sort by "+fname,
		))
	}

	// filter params with operator variants per field type
	for _, fname := range sortedFieldKeys(res) {
		fd := res.Fields[fname]
		baseSchema := oaFieldType(fd)
		params = append(params, oaQueryParamDesc(
			"filter["+fname+"]",
			baseSchema,
			oaFilterDesc(fname, fd.Type),
		))
		// add operator variants for applicable types
		for _, op := range oaOpsForType(fd.Type) {
			if op == "eq" {
				continue // already covered by filter[field]
			}
			params = append(params, oaQueryParamDesc(
				"filter["+fname+"]["+op+"]",
				baseSchema,
				oaOpDesc(fname, op),
			))
		}
	}

	return map[string]any{
		"operationId": "list" + title,
		"summary":     "List " + name,
		"tags":        []string{name},
		"parameters":  params,
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(title + "ListResponse")),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
		},
	}
}

func oaCreateOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "create" + title,
		"summary":     "Create " + name,
		"tags":        []string{name},
		"requestBody": map[string]any{
			"required": true,
			"content":  oaJSONContent(oaSchemaRef(title + "Input")),
		},
		"responses": map[string]any{
			"201": map[string]any{
				"description": "Created",
				"content":     oaJSONContent(oaSchemaRef(title)),
			},
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"422": oaRespRef("Error422"),
		},
	}
}

func oaGetOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "get" + title,
		"summary":     "Get " + name + " by ID",
		"tags":        []string{name},
		"parameters":  []any{oaPathIDParam()},
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(title)),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
		},
	}
}

// oaReplaceOp documents PUT /api/{resource}/{id} — full replacement. It consumes
// the same Input schema as create (all required fields enforced); omitted optional
// fields are reset to null on the server.
func oaReplaceOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "replace" + title,
		"summary":     "Replace " + name,
		"description": "Full replacement: all required fields must be present; omitted optional fields are set to null.",
		"tags":        []string{name},
		"parameters":  []any{oaPathIDParam()},
		"requestBody": map[string]any{
			"required": true,
			"content":  oaJSONContent(oaSchemaRef(title + "Input")),
		},
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(title)),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
			"409": oaRespRef("Error409"),
			"413": oaRespRef("Error413"),
			"422": oaRespRef("Error422"),
		},
	}
}

// oaUpdateOp documents PATCH /api/{resource}/{id} — partial update. It consumes the
// PatchInput schema (every field optional); only the fields present in the body are
// modified.
func oaUpdateOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "update" + title,
		"summary":     "Partially update " + name,
		"description": "Partial update: only the fields present in the body are modified; the rest are left unchanged.",
		"tags":        []string{name},
		"parameters":  []any{oaPathIDParam()},
		"requestBody": map[string]any{
			"required": true,
			"content":  oaJSONContent(oaSchemaRef(title + "PatchInput")),
		},
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(title)),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
			"409": oaRespRef("Error409"),
			"413": oaRespRef("Error413"),
			"422": oaRespRef("Error422"),
		},
	}
}

func oaDeleteOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "delete" + title,
		"summary":     "Delete " + name,
		"tags":        []string{name},
		"parameters":  []any{oaPathIDParam()},
		"responses": map[string]any{
			"204": map[string]any{"description": "Deleted"},
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
		},
	}
}

func oaSubresourceOp(resName, resTitle, relName, relTitle, relResource, fieldName string) map[string]any {
	return map[string]any{
		"operationId": "get" + resTitle + toPascalCase(relName),
		"summary":     "Get " + relResource + " related to " + resName + " via " + fieldName,
		"tags":        []string{resName},
		"parameters":  []any{oaPathIDParam()},
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(relTitle)),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
		},
	}
}

// ── components ───────────────────────────────────────────────────────────────

func buildOAComponents(s *schema.APISchema) map[string]any {
	schemas := map[string]any{
		"ErrorResponse": map[string]any{
			"type":     "object",
			"required": []string{"error"},
			"properties": map[string]any{
				"error": map[string]any{"type": "string"},
			},
		},
		// Matches the actual list response: page/per_page/has_next/has_prev. No
		// total/total_pages — COUNT(*) was removed from the list handler for
		// performance, so the response never carries row totals.
		"PaginationMeta": map[string]any{
			"type":     "object",
			"required": []string{"page", "per_page", "has_next", "has_prev"},
			"properties": map[string]any{
				"page":     map[string]any{"type": "integer"},
				"per_page": map[string]any{"type": "integer"},
				"has_next": map[string]any{"type": "boolean"},
				"has_prev": map[string]any{"type": "boolean"},
			},
		},
		"PaginationLinks": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"self":  map[string]any{"type": "string"},
				"first": map[string]any{"type": "string"},
				"last":  map[string]any{"type": "string"},
				"prev":  map[string]any{"type": "string", "nullable": true},
				"next":  map[string]any{"type": "string", "nullable": true},
			},
		},
	}

	for _, name := range sortedResourceKeys(s) {
		res := s.Resources[name]
		title := toPascalCase(name)
		schemas[title] = oaResourceSchema(&res, true)
		schemas[title+"Input"] = oaResourceSchema(&res, false)
		// PatchInput mirrors Input but with every field optional (no required list),
		// matching PATCH semantics (only supplied fields are updated).
		patchInput := oaResourceSchema(&res, false)
		delete(patchInput, "required")
		schemas[title+"PatchInput"] = patchInput
		schemas[title+"ListResponse"] = map[string]any{
			"type": "object",
			"properties": map[string]any{
				"data": map[string]any{
					"type":  "array",
					"items": oaSchemaRef(title),
				},
				"meta":  oaSchemaRef("PaginationMeta"),
				"links": oaSchemaRef("PaginationLinks"),
			},
		}
	}

	return map[string]any{
		"securitySchemes": map[string]any{
			"bearerAuth": map[string]any{
				"type":         "http",
				"scheme":       "bearer",
				"bearerFormat": "JWT",
			},
		},
		"schemas": schemas,
		"responses": map[string]any{
			"Error400": oaErrResp("Bad request — invalid input, UUID format, or query parameter"),
			"Error401": oaErrResp("Authentication required — include a valid Bearer token"),
			"Error403": oaErrResp("Insufficient permissions for this action"),
			"Error404": oaErrResp("Resource not found"),
			"Error409": oaErrResp("Conflict — a unique constraint would be violated"),
			"Error413": oaErrResp("Request body too large (1 MiB limit)"),
			"Error422": oaErrResp("Validation failed, or a before_create/before_update hook rejected the request"),
		},
	}
}

func oaResourceSchema(res *schema.ResourceSchema, includeAuto bool) map[string]any {
	props := map[string]any{}
	if includeAuto {
		props["id"] = map[string]any{"type": "string", "format": "uuid", "readOnly": true}
	}
	var required []string

	for _, fname := range sortedFieldKeys(res) {
		fd := res.Fields[fname]
		if fd.Auto && !includeAuto {
			continue
		}
		props[fname] = oaFieldType(fd)
		if fd.Required && !fd.Auto {
			required = append(required, fname)
		}
	}

	out := map[string]any{
		"type":       "object",
		"properties": props,
	}
	if len(required) > 0 {
		sort.Strings(required)
		out["required"] = required
	}
	return out
}

// oaFieldType maps a FieldDef to an OpenAPI type schema object.
func oaFieldType(fd schema.FieldDef) map[string]any {
	switch fd.Type {
	case "string", "text":
		m := map[string]any{"type": "string"}
		if len(fd.Enum) > 0 {
			m["enum"] = fd.Enum
		}
		return m
	case "int":
		return map[string]any{"type": "integer", "format": "int32"}
	case "int64":
		return map[string]any{"type": "integer", "format": "int64"}
	case "float64":
		return map[string]any{"type": "number", "format": "double"}
	case "bool":
		return map[string]any{"type": "boolean"}
	case "uuid":
		return map[string]any{"type": "string", "format": "uuid"}
	case "time":
		return map[string]any{"type": "string", "format": "date-time"}
	default:
		return map[string]any{"type": "string"}
	}
}

func oaSortEnum(res *schema.ResourceSchema) []string {
	enum := []string{"id"}
	enum = append(enum, sortedFieldKeys(res)...)
	return enum
}

func oaOpsForType(fieldType string) []string {
	switch fieldType {
	case "string", "text":
		return []string{"eq", "partial"}
	case "int", "int64", "float64":
		return []string{"eq", "gt", "gte", "lt", "lte"}
	case "time":
		return []string{"eq", "after", "before", "gte", "lte"}
	default:
		return []string{"eq"}
	}
}

func oaFilterDesc(field, fieldType string) string {
	ops := oaOpsForType(fieldType)
	return "Filter by " + field + ". Operators: " + strings.Join(ops, ", ")
}

func oaOpDesc(field, op string) string {
	switch op {
	case "partial":
		return "Filter " + field + " using ILIKE (case-insensitive substring match)"
	case "gte":
		return "Filter " + field + " ≥ value"
	case "lte":
		return "Filter " + field + " ≤ value"
	case "gt":
		return "Filter " + field + " > value"
	case "lt":
		return "Filter " + field + " < value"
	case "after":
		return "Filter " + field + " strictly after the given date-time"
	case "before":
		return "Filter " + field + " strictly before the given date-time"
	default:
		return "Filter " + field + " by exact value"
	}
}

// ── helpers ──────────────────────────────────────────────────────────────────

func oaSchemaRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/schemas/" + name}
}

func oaRespRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/responses/" + name}
}

func oaJSONContent(s map[string]any) map[string]any {
	return map[string]any{"application/json": map[string]any{"schema": s}}
}

func oaSuccessResp(s map[string]any) map[string]any {
	return map[string]any{"description": "Success", "content": oaJSONContent(s)}
}

func oaErrResp(desc string) map[string]any {
	return map[string]any{"description": desc, "content": oaJSONContent(oaSchemaRef("ErrorResponse"))}
}

func oaQueryParam(name string, s map[string]any) map[string]any {
	return map[string]any{"name": name, "in": "query", "schema": s}
}

func oaQueryParamDesc(name string, s map[string]any, desc string) map[string]any {
	return map[string]any{"name": name, "in": "query", "description": desc, "schema": s}
}

func oaPathIDParam() map[string]any {
	return map[string]any{
		"name":     "id",
		"in":       "path",
		"required": true,
		"schema":   map[string]any{"type": "string", "format": "uuid"},
	}
}

func sortedResourceKeys(s *schema.APISchema) []string {
	keys := make([]string, 0, len(s.Resources))
	for k := range s.Resources {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedFieldKeys(res *schema.ResourceSchema) []string {
	keys := make([]string, 0, len(res.Fields))
	for k := range res.Fields {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
