package codegen

import (
	"encoding/json"
	"sort"
	"strings"

	"github.com/appximo/appximo/pkg/schema"
	"gopkg.in/yaml.v3"
)

type openAPISpec struct {
	OpenAPI  string           `yaml:"openapi" json:"openapi"`
	Info     map[string]any   `yaml:"info" json:"info"`
	Servers  []map[string]any `yaml:"servers,omitempty" json:"servers,omitempty"`
	Security []map[string]any `yaml:"security" json:"security"`
	// VirtualResources declares the ENGINE-PROVIDED resources that exist on
	// every app without being schema resources — today the built-in `files`
	// store (absent when a schema resource shadows it). A generic tool needs
	// this to offer file management and to know the RBAC grant vocabulary;
	// its absence was gap #4 of PATRON-BACKOFFICE §6 (and the same blind spot
	// behind Studio's ST1). Keys: name → {actions, description}.
	VirtualResources map[string]any `yaml:"x-appximo-virtual-resources,omitempty" json:"x-appximo-virtual-resources,omitempty"`
	Paths            map[string]any `yaml:"paths" json:"paths"`
	Components       map[string]any `yaml:"components" json:"components"`
}

// buildOASpec assembles the full OpenAPI 3.0.3 document object for an APISchema
// plus the app's registered custom routes (nil for a pure `serve` binary — the
// document is then byte-identical to before ENG-33). It is the single source of
// truth shared by the YAML and JSON marshallers, so the `appximo openapi` CLI
// and the served /openapi.json are byte-for-byte the same contract in two
// encodings.
func buildOASpec(s *schema.APISchema, baseURL string, routes []CustomRoute) openAPISpec {
	if baseURL == "" {
		baseURL = "/"
	}
	paths := buildOAPaths(s)
	addOACustomPaths(paths, routes)
	var virtual map[string]any
	if _, shadowed := s.Resources["files"]; !shadowed {
		virtual = map[string]any{
			"files": map[string]any{
				"actions": []string{"read", "create", "delete"},
				"description": "the built-in content-addressable file store (/api/files) — " +
					"grantable in RBAC exactly like a schema resource (actions only, no " +
					"conditions/fields); not declared in the schema",
			},
		}
	}
	return openAPISpec{
		VirtualResources: virtual,
		OpenAPI:          "3.0.3",
		Info: map[string]any{
			"title":   s.Name,
			"version": s.Version,
			"description": "Generated by Appximo — https://github.com/appximo/appximo. " +
				"Building a client or frontend with an AI agent? The engine prints its full agent-facing contract: " +
				"`appximo spec` (the schema grammar), `appximo backend-spec` (custom handlers/hooks/jobs), " +
				"`appximo frontend-spec` (the API contract a UI consumes, error→screen-state mapping, files).",
		},
		Servers:    []map[string]any{{"url": baseURL, "description": "API server"}},
		Security:   []map[string]any{{"bearerAuth": []string{}}},
		Paths:      paths,
		Components: buildOAComponents(s),
	}
}

// GenerateOpenAPI produces an OpenAPI 3.0.3 YAML document from an APISchema.
// baseURL is set as the server URL (defaults to "/" when empty).
func GenerateOpenAPI(s *schema.APISchema, baseURL string) ([]byte, error) {
	return GenerateOpenAPIWithRoutes(s, baseURL, nil)
}

// GenerateOpenAPIJSON produces the SAME OpenAPI 3.0.3 document as GenerateOpenAPI
// but JSON-encoded — the format Swagger UI and most client generators consume. The
// engine serves it at GET /openapi.json.
func GenerateOpenAPIJSON(s *schema.APISchema, baseURL string) ([]byte, error) {
	return GenerateOpenAPIJSONWithRoutes(s, baseURL, nil)
}

// GenerateOpenAPIWithRoutes is GenerateOpenAPI plus the app's registered custom
// routes as path items (ENG-33) — what a framework-mode App serves, so the
// contract covers the WHOLE surface, not only the generated half.
func GenerateOpenAPIWithRoutes(s *schema.APISchema, baseURL string, routes []CustomRoute) ([]byte, error) {
	return yaml.Marshal(buildOASpec(s, baseURL, routes))
}

// GenerateOpenAPIJSONWithRoutes is the JSON encoding of GenerateOpenAPIWithRoutes.
func GenerateOpenAPIJSONWithRoutes(s *schema.APISchema, baseURL string, routes []CustomRoute) ([]byte, error) {
	return json.MarshalIndent(buildOASpec(s, baseURL, routes), "", "  ")
}

// ── paths ─────────────────────────────────────────────────────────────────────

func buildOAPaths(s *schema.APISchema) map[string]any {
	paths := map[string]any{}
	// Auth-as-product endpoints (AUTH-CORE-V1 …): always part of the engine's API
	// surface, independent of the schema, so they are always documented.
	addOAAuthPaths(paths)
	// File store routes exist whenever no schema resource is literally named "files".
	if _, taken := s.Resources["files"]; !taken {
		addOAFilePaths(paths)
	}
	// The anonymous surface (ADR-026): a resource with a rbac.public read grant
	// marks its READ operations `security: []` + `x-public: true`, so a generic
	// tool discovers that no token is needed there (the write ops keep the
	// global bearer requirement — the public surface is read-only).
	markPublic := func(op map[string]any) map[string]any {
		op["security"] = []any{}
		op["x-public"] = true
		return op
	}
	for _, name := range sortedResourceKeys(s) {
		res := s.Resources[name]
		title := toPascalCase(name)
		_, publicRead := s.RBAC.Public[name]
		listOp, getOp := oaListOp(name, title, &res), oaGetOp(name, title)
		if publicRead {
			listOp, getOp = markPublic(listOp), markPublic(getOp)
		}
		paths["/api/"+name] = map[string]any{
			"get":  listOp,
			"post": oaCreateOp(name, title),
		}
		// The aggregate endpoint (G3) is a read of the same scoped set, so it
		// is public exactly when the list is (ADR-026 covers aggregates).
		aggOp := oaAggregateOp(name, title, &res)
		if publicRead {
			aggOp = markPublic(aggOp)
		}
		paths["/api/"+name+"/aggregate"] = map[string]any{
			"get": aggOp,
		}
		paths["/api/"+name+"/{id}"] = map[string]any{
			"get":    getOp,
			"put":    oaReplaceOp(name, title),
			"patch":  oaUpdateOp(name, title),
			"delete": oaDeleteOp(name, title),
		}
		// subresource paths (public only when the TARGET is publicly readable
		// too — the subroute enforces the target's RBAC, SEC-AUDIT-V1).
		for _, fname := range sortedFieldKeys(&res) {
			fd := res.Fields[fname]
			if fd.Relation == "" {
				continue
			}
			relName := schema.RelationSubroute(fname) // the ONE derivation, load-validated against collisions
			relTitle := toPascalCase(fd.Relation)
			subOp := oaSubresourceOp(name, title, relName, relTitle, fd.Relation, fname)
			if publicRead {
				if _, targetPublic := s.RBAC.Public[fd.Relation]; targetPublic {
					subOp = markPublic(subOp)
				}
			}
			paths["/api/"+name+"/{id}/"+relName] = map[string]any{
				"get": subOp,
			}
		}
	}
	return paths
}

// addOAAuthPaths documents the auth-as-product endpoints. The unauthenticated
// flows (signup/login/refresh/reset/verify) carry `security: []` to OVERRIDE the
// global bearerAuth requirement (they run before a token exists); the MFA enroll
// endpoints keep the global bearer requirement. Host is the tenant subdomain.
func addOAAuthPaths(paths map[string]any) {
	noAuth := []any{} // security: [] — overrides the global bearerAuth

	paths["/auth/signup"] = map[string]any{"post": map[string]any{
		"operationId": "authSignup",
		"summary":     "Sign up a new user in the tenant (public signup must be enabled)",
		"tags":        []string{"auth"},
		"security":    noAuth,
		"requestBody": oaReqBody("AuthCredentials"),
		"responses": map[string]any{
			"201": oaSuccessResp(oaSchemaRef("AuthResult")),
			"403": oaRespRef("Error403"), "409": oaRespRef("Error409"), "422": oaRespRef("Error422"),
		},
	}}
	paths["/auth/login"] = map[string]any{"post": map[string]any{
		"operationId": "authLogin",
		"summary":     "Log in with email + password; returns a JWT (or an MFA challenge)",
		"description": "On success returns {user, token}. If the user has TOTP MFA enabled, returns {mfa_required:true, mfa_token} instead — complete the login at /auth/mfa/verify. Wrong password and unknown email are indistinguishable (401).",
		"tags":        []string{"auth"},
		"security":    noAuth,
		"requestBody": oaReqBody("AuthCredentials"),
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef("AuthResult")),
			"401": oaRespRef("Error401"), "403": oaRespRef("Error403"), "429": oaRespRef("Error429"),
		},
	}}
	paths["/auth/refresh"] = map[string]any{"post": map[string]any{
		"operationId": "authRefresh",
		"summary":     "Re-mint a fresh JWT from a still-valid one",
		"description": "Send the current token in the Authorization: Bearer header OR a {\"token\":\"…\"} body. Returns {token} with a new expiry. Stateless: the old token keeps working until its own exp.",
		"tags":        []string{"auth"},
		"security":    noAuth,
		"requestBody": oaReqBodyOptional("RefreshRequest"),
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef("TokenResponse")),
			"400": oaRespRef("Error400"), "401": oaRespRef("Error401"),
		},
	}}
	paths["/auth/reset/request"] = map[string]any{"post": map[string]any{
		"operationId": "authResetRequest",
		"summary":     "Request a password-reset email (uniform anti-enumeration response)",
		"tags":        []string{"auth"}, "security": noAuth,
		"requestBody": oaReqBody("EmailRequest"),
		"responses":   map[string]any{"200": oaSuccessResp(oaSchemaRef("MessageResponse")), "429": oaRespRef("Error429")},
	}}
	paths["/auth/reset/confirm"] = map[string]any{"post": map[string]any{
		"operationId": "authResetConfirm",
		"summary":     "Consume a reset token and set a new password",
		"tags":        []string{"auth"}, "security": noAuth,
		"requestBody": oaReqBody("ResetConfirmRequest"),
		"responses":   map[string]any{"200": oaSuccessResp(oaSchemaRef("MessageResponse")), "400": oaRespRef("Error400"), "422": oaRespRef("Error422")},
	}}
	paths["/auth/verify/request"] = map[string]any{"post": map[string]any{
		"operationId": "authVerifyRequest",
		"summary":     "Request an email-verification link (uniform anti-enumeration response)",
		"tags":        []string{"auth"}, "security": noAuth,
		"requestBody": oaReqBody("EmailRequest"),
		"responses":   map[string]any{"200": oaSuccessResp(oaSchemaRef("MessageResponse")), "429": oaRespRef("Error429")},
	}}
	paths["/auth/verify"] = map[string]any{
		"get": map[string]any{
			"operationId": "authVerifyLink",
			"summary":     "Verify an email via the clickable link token",
			"tags":        []string{"auth"}, "security": noAuth,
			"parameters": []any{oaQueryParamDesc("token", map[string]any{"type": "string"}, "the single-use verification token from the email link")},
			"responses":  map[string]any{"200": oaSuccessResp(oaSchemaRef("MessageResponse")), "400": oaRespRef("Error400")},
		},
		"post": map[string]any{
			"operationId": "authVerifyConfirm",
			"summary":     "Verify an email by posting the token",
			"tags":        []string{"auth"}, "security": noAuth,
			"requestBody": oaReqBodyOptional("TokenRequest"),
			"responses":   map[string]any{"200": oaSuccessResp(oaSchemaRef("MessageResponse")), "400": oaRespRef("Error400")},
		},
	}
	paths["/auth/mfa/verify"] = map[string]any{"post": map[string]any{
		"operationId": "authMFAVerify",
		"summary":     "Complete a two-step login with a TOTP or backup code",
		"tags":        []string{"auth"}, "security": noAuth,
		"requestBody": oaReqBody("MFAVerifyRequest"),
		"responses":   map[string]any{"200": oaSuccessResp(oaSchemaRef("AuthResult")), "401": oaRespRef("Error401"), "429": oaRespRef("Error429")},
	}}
}

// addOAFilePaths documents the built-in content-addressable file store routes.
func addOAFilePaths(paths map[string]any) {
	// Every operation of the built-in store is tagged as belonging to the
	// VIRTUAL `files` resource (x-appximo-virtual-resource), pairing with the
	// document-root x-appximo-virtual-resources declaration — so a generic
	// tool can group them and offer file management without hardcoding.
	paths["/api/files"] = map[string]any{"post": map[string]any{
		"x-appximo-virtual-resource": "files",
		"operationId":                "uploadFile",
		"summary":                    "Upload a file (multipart, streamed + content-addressed)",
		"tags":                       []string{"files"},
		"requestBody": map[string]any{
			"required": true,
			"content": map[string]any{"multipart/form-data": map[string]any{"schema": map[string]any{
				"type":       "object",
				"properties": map[string]any{"file": map[string]any{"type": "string", "format": "binary"}},
				"required":   []string{"file"},
			}}},
		},
		"responses": map[string]any{
			"201": map[string]any{"description": "Created", "content": oaJSONContent(oaSchemaRef("FileUploadResult"))},
			"401": oaRespRef("Error401"), "403": oaRespRef("Error403"), "413": oaRespRef("Error413"),
		},
	}}
	paths["/api/files/{id}"] = map[string]any{
		"get": map[string]any{
			"x-appximo-virtual-resource": "files",
			"operationId":                "downloadFile",
			"summary":                    "Download a file blob by id (Range/ETag honored; the S3 backend may answer 302 to a short-lived presigned URL)",
			"tags":                       []string{"files"},
			"parameters":                 []any{oaPathIDParam()},
			"responses": map[string]any{
				"200": map[string]any{"description": "The file bytes", "content": map[string]any{
					"application/octet-stream": map[string]any{"schema": map[string]any{"type": "string", "format": "binary"}},
				}},
				"206": map[string]any{"description": "Partial content (Range request)"},
				"302": map[string]any{"description": "Redirect to a short-lived presigned storage URL (S3 backend, redirect mode)"},
				"401": oaRespRef("Error401"), "403": oaRespRef("Error403"), "404": oaRespRef("Error404"),
			},
		},
		"delete": map[string]any{
			"x-appximo-virtual-resource": "files",
			"operationId":                "deleteFile",
			"summary":                    "Delete a file (metadata row + blob when no other upload references the same content)",
			"tags":                       []string{"files"},
			"parameters":                 []any{oaPathIDParam()},
			"responses": map[string]any{
				"204": map[string]any{"description": "Deleted"},
				"401": oaRespRef("Error401"), "403": oaRespRef("Error403"), "404": oaRespRef("Error404"),
			},
		},
	}
	paths["/api/files/{id}/url"] = map[string]any{"get": map[string]any{
		"x-appximo-virtual-resource": "files",
		"operationId":                "signFileURL",
		"summary":                    "Mint a short-lived signed download URL (engine token URL on the local backend; native presigned URL on S3)",
		"tags":                       []string{"files"},
		"parameters":                 []any{oaPathIDParam()},
		"responses": map[string]any{
			"200": map[string]any{"description": "Signed URL", "content": oaJSONContent(map[string]any{
				"type": "object",
				"properties": map[string]any{
					"url":        map[string]any{"type": "string"},
					"expires_in": map[string]any{"type": "integer", "description": "seconds"},
				},
			})},
			"401": oaRespRef("Error401"), "403": oaRespRef("Error403"), "404": oaRespRef("Error404"),
		},
	}}
}

func oaReqBody(schemaName string) map[string]any {
	return map[string]any{"required": true, "content": oaJSONContent(oaSchemaRef(schemaName))}
}

func oaReqBodyOptional(schemaName string) map[string]any {
	return map[string]any{"required": false, "content": oaJSONContent(oaSchemaRef(schemaName))}
}

func oaListOp(name, title string, res *schema.ResourceSchema) map[string]any {
	params := []any{
		oaQueryParam("page", map[string]any{
			"type":    "integer",
			"default": 1,
			"minimum": 1,
		}),
		oaQueryParam("per_page", map[string]any{
			"type":    "integer",
			"default": 20,
			"minimum": 1,
			"maximum": 100,
		}),
		oaQueryParamDesc("sort", map[string]any{"type": "string", "enum": oaSortEnum(res)},
			"Field to sort by (legacy). Prefer order[field]=asc|desc"),
		oaQueryParamDesc("order", map[string]any{"type": "string", "enum": []string{"asc", "desc"}, "default": "asc"},
			"Sort direction for the sort field (legacy)"),
		oaQueryParamDesc("search", map[string]any{"type": "string"},
			"Full-text search across all string fields (ILIKE)"),
	}

	// order[field] params
	for _, fname := range sortedFieldKeys(res) {
		params = append(params, oaQueryParamDesc(
			"order["+fname+"]",
			map[string]any{"type": "string", "enum": []string{"asc", "desc"}},
			"Sort by "+fname,
		))
	}

	params = append(params, oaFilterParams(res)...)

	return map[string]any{
		"operationId": "list" + title,
		"summary":     "List " + name,
		"tags":        []string{name},
		"parameters":  params,
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(title + "ListResponse")),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
		},
	}
}

// oaFilterParams builds the filter[...] query parameters a resource accepts —
// shared by the list operation and the aggregate operation (ENG-40), which
// scope by the same filter grammar.
func oaFilterParams(res *schema.ResourceSchema) []any {
	var params []any
	for _, fname := range sortedFieldKeys(res) {
		fd := res.Fields[fname]
		baseSchema := oaFieldType(fd)
		params = append(params, oaQueryParamDesc(
			"filter["+fname+"]",
			baseSchema,
			oaFilterDesc(fname, fd.Type),
		))
		// add operator variants for applicable types
		for _, op := range oaOpsForType(fd.Type) {
			if op == "eq" {
				continue // already covered by filter[field]
			}
			params = append(params, oaQueryParamDesc(
				"filter["+fname+"]["+op+"]",
				baseSchema,
				oaOpDesc(fname, op),
			))
		}
		// is_null (SCHEMA-6) applies to every NULLABLE column — a required
		// field is NOT NULL and the engine rejects the operator on it, so the
		// spec does not advertise it there.
		if !fd.Required {
			params = append(params, oaQueryParamDesc(
				"filter["+fname+"][is_null]",
				map[string]any{"type": "boolean"},
				"Filter "+fname+" by nullness: true → IS NULL, false → IS NOT NULL",
			))
		}
	}
	return params
}

// oaAggregateOp documents GET /api/{resource}/aggregate (ENG-40: the endpoint
// shipped in G3 but never appeared in the served contract). The parameter
// vocabulary and per-type eligibility mirror query.BuildAggregate exactly:
// sum/avg over numeric fields, min/max over numeric or time, group_by over
// anything but json/jsonb, plus the same filter[...]/search grammar as the
// list — a parameter the endpoint cannot honor (page, sort, order…) is a 400
// and is deliberately NOT advertised here.
func oaAggregateOp(name, title string, res *schema.ResourceSchema) map[string]any {
	var numeric, minmax, groupable []string
	for _, fname := range sortedFieldKeys(res) {
		switch res.Fields[fname].Type {
		case "int", "int64", "float64":
			numeric = append(numeric, fname)
			minmax = append(minmax, fname)
		case "time":
			minmax = append(minmax, fname)
		}
		if t := res.Fields[fname].Type; t != "json" && t != "jsonb" {
			groupable = append(groupable, fname)
		}
	}
	params := []any{
		oaQueryParamDesc("count", map[string]any{"type": "boolean"},
			"COUNT(*) over the filtered, RBAC-scoped set. Bare ?count or count=true → on; count=false → off"),
	}
	if len(numeric) > 0 {
		list := strings.Join(numeric, ", ")
		params = append(params,
			oaQueryParamDesc("sum", map[string]any{"type": "string"},
				"Comma-separated numeric fields to SUM (eligible: "+list+")"),
			oaQueryParamDesc("avg", map[string]any{"type": "string"},
				"Comma-separated numeric fields to AVG (eligible: "+list+")"),
		)
	}
	if len(minmax) > 0 {
		list := strings.Join(minmax, ", ")
		params = append(params,
			oaQueryParamDesc("min", map[string]any{"type": "string"},
				"Comma-separated fields to MIN — numeric or time (eligible: "+list+")"),
			oaQueryParamDesc("max", map[string]any{"type": "string"},
				"Comma-separated fields to MAX — numeric or time (eligible: "+list+")"),
		)
	}
	if len(groupable) > 0 {
		params = append(params, oaQueryParamDesc("group_by", map[string]any{"type": "string"},
			"Comma-separated fields to GROUP BY (eligible: "+strings.Join(groupable, ", ")+"). Requires at least one aggregate function. Response becomes {\"groups\":[…]}"))
	}
	params = append(params, oaQueryParamDesc("search", map[string]any{"type": "string"},
		"Case-insensitive substring match across the resource's string/text fields (same as the list)"))
	params = append(params, oaFilterParams(res)...)
	return map[string]any{
		"operationId": "aggregate" + title,
		"summary":     "Aggregate " + name + " (count/sum/avg/min/max, optional group_by)",
		"description": "Runs the fixed aggregate functions over " + name + ", scoped EXACTLY like a list read: the role's row condition, field allowlist and the same filter grammar apply. List-only parameters (page, per_page, sort, order, after, before, include) are a 400 here.",
		"tags":        []string{name},
		"parameters":  params,
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef("AggregateResponse")),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
		},
	}
}

func oaCreateOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "create" + title,
		"summary":     "Create " + name,
		"tags":        []string{name},
		"requestBody": map[string]any{
			"required": true,
			"content":  oaJSONContent(oaSchemaRef(title + "Input")),
		},
		"responses": map[string]any{
			"201": map[string]any{
				"description": "Created",
				"content":     oaJSONContent(oaSchemaRef(title)),
			},
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"422": oaRespRef("Error422"),
		},
	}
}

func oaGetOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "get" + title,
		"summary":     "Get " + name + " by ID",
		"tags":        []string{name},
		"parameters":  []any{oaPathIDParam()},
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(title)),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
		},
	}
}

// oaReplaceOp documents PUT /api/{resource}/{id} — full replacement. It consumes
// the same Input schema as create (all required fields enforced); omitted optional
// fields are reset to null on the server.
func oaReplaceOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "replace" + title,
		"summary":     "Replace " + name,
		"description": "Full replacement: all required fields must be present; omitted optional fields are set to null.",
		"tags":        []string{name},
		"parameters":  []any{oaPathIDParam()},
		"requestBody": map[string]any{
			"required": true,
			"content":  oaJSONContent(oaSchemaRef(title + "Input")),
		},
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(title)),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
			"409": oaRespRef("Error409"),
			"413": oaRespRef("Error413"),
			"422": oaRespRef("Error422"),
		},
	}
}

// oaUpdateOp documents PATCH /api/{resource}/{id} — partial update. It consumes the
// PatchInput schema (every field optional); only the fields present in the body are
// modified.
func oaUpdateOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "update" + title,
		"summary":     "Partially update " + name,
		"description": "Partial update: only the fields present in the body are modified; the rest are left unchanged.",
		"tags":        []string{name},
		"parameters":  []any{oaPathIDParam()},
		"requestBody": map[string]any{
			"required": true,
			"content":  oaJSONContent(oaSchemaRef(title + "PatchInput")),
		},
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(title)),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
			"409": oaRespRef("Error409"),
			"413": oaRespRef("Error413"),
			"422": oaRespRef("Error422"),
		},
	}
}

func oaDeleteOp(name, title string) map[string]any {
	return map[string]any{
		"operationId": "delete" + title,
		"summary":     "Delete " + name,
		"tags":        []string{name},
		"parameters":  []any{oaPathIDParam()},
		"responses": map[string]any{
			"204": map[string]any{"description": "Deleted"},
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
		},
	}
}

func oaSubresourceOp(resName, resTitle, relName, relTitle, relResource, fieldName string) map[string]any {
	return map[string]any{
		"operationId": "get" + resTitle + toPascalCase(relName),
		"summary":     "Get " + relResource + " related to " + resName + " via " + fieldName,
		"tags":        []string{resName},
		"parameters":  []any{oaPathIDParam()},
		"responses": map[string]any{
			"200": oaSuccessResp(oaSchemaRef(relTitle)),
			"400": oaRespRef("Error400"),
			"401": oaRespRef("Error401"),
			"403": oaRespRef("Error403"),
			"404": oaRespRef("Error404"),
		},
	}
}

// ── components ───────────────────────────────────────────────────────────────

func buildOAComponents(s *schema.APISchema) map[string]any {
	schemas := map[string]any{
		"ErrorResponse": map[string]any{
			"type":     "object",
			"required": []string{"error"},
			"properties": map[string]any{
				"error": map[string]any{"type": "string"},
			},
		},
		// The declarative-validation 422 body: every failing field reported at once.
		// Matches builder.go writeValidationErrs: {"error":"validation_failed","fields":[{field,rule,message}]}.
		"ValidationError": map[string]any{
			"type":     "object",
			"required": []string{"field", "rule", "message"},
			"properties": map[string]any{
				"field":   map[string]any{"type": "string"},
				"rule":    map[string]any{"type": "string"},
				"message": map[string]any{"type": "string"},
			},
		},
		"ValidationErrorResponse": map[string]any{
			"type":     "object",
			"required": []string{"error", "fields"},
			"properties": map[string]any{
				"error":  map[string]any{"type": "string", "example": "validation_failed"},
				"fields": map[string]any{"type": "array", "items": oaSchemaRef("ValidationError")},
			},
		},
		// ENG-40: the aggregate endpoint's response. Without group_by, ONE
		// object carrying only the requested keys; with group_by, {"groups":
		// [...]} where each group carries its group-by field values plus the
		// same aggregate keys. sum/avg values are numbers; min/max values are
		// numbers or timestamps depending on the field's type.
		"AggregateResponse": map[string]any{
			"type":        "object",
			"description": "Without group_by: one object with only the requested keys (count, sum, avg, min, max). With group_by: {\"groups\": [...]} — each group carries its group-by field values plus the requested aggregate keys.",
			"properties": map[string]any{
				"count": map[string]any{"type": "integer"},
				"sum":   map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "number"}},
				"avg":   map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "number"}},
				"min":   map[string]any{"type": "object", "additionalProperties": map[string]any{}},
				"max":   map[string]any{"type": "object", "additionalProperties": map[string]any{}},
				"groups": map[string]any{
					"type":  "array",
					"items": map[string]any{"type": "object", "additionalProperties": true},
				},
			},
		},
		// Matches the actual list response meta. page/has_prev are ABSENT on a
		// cursor (?after/?before) request — keyset pagination has no page number,
		// and meta must not invent one (ENG-15). total/total_pages appear only
		// when the caller opted in with ?count=true (ENG-23); no `links` object —
		// the live engine emits meta only (keyset pages via ?after=<last id>).
		"PaginationMeta": map[string]any{
			"type":     "object",
			"required": []string{"per_page", "has_next"},
			"properties": map[string]any{
				"page":        map[string]any{"type": "integer", "description": "absent on a cursor (?after/?before) request — a cursor request has no page number"},
				"per_page":    map[string]any{"type": "integer"},
				"has_next":    map[string]any{"type": "boolean", "description": "more rows exist after this page (continue with ?after=<last item's id>)"},
				"has_prev":    map[string]any{"type": "boolean", "description": "absent on a cursor request"},
				"total":       map[string]any{"type": "integer", "description": "present only with ?count=true — the COUNT(*) over the same filtered, RBAC-scoped set"},
				"total_pages": map[string]any{"type": "integer", "description": "present only with ?count=true"},
			},
		},
	}
	addOAAuthSchemas(schemas)

	for _, name := range sortedResourceKeys(s) {
		res := s.Resources[name]
		title := toPascalCase(name)
		schemas[title] = oaResourceSchema(&res, true)
		schemas[title+"Input"] = oaResourceSchema(&res, false)
		// PatchInput mirrors Input but with every field optional (no required list),
		// matching PATCH semantics (only supplied fields are updated).
		patchInput := oaResourceSchema(&res, false)
		delete(patchInput, "required")
		schemas[title+"PatchInput"] = patchInput
		schemas[title+"ListResponse"] = map[string]any{
			"type": "object",
			"properties": map[string]any{
				"data": map[string]any{
					"type":  "array",
					"items": oaSchemaRef(title),
				},
				"meta": oaSchemaRef("PaginationMeta"),
			},
		}
	}

	return map[string]any{
		"securitySchemes": map[string]any{
			"bearerAuth": map[string]any{
				"type":         "http",
				"scheme":       "bearer",
				"bearerFormat": "JWT",
			},
		},
		"schemas": schemas,
		"responses": map[string]any{
			"Error400": oaErrResp("Bad request — invalid input, UUID format, or query parameter"),
			"Error401": oaErrResp("Authentication required — include a valid Bearer token"),
			"Error403": oaErrResp("Insufficient permissions for this action"),
			"Error404": oaErrResp("Resource not found"),
			"Error409": oaErrResp("Conflict — a unique constraint would be violated"),
			"Error413": oaErrResp("Request body too large (1 MiB limit)"),
			"Error429": oaErrResp("Too many requests — rate or login-attempt limit exceeded (see Retry-After)"),
			"Error422": map[string]any{
				"description": "Validation failed (every offending field is listed), or a before_create/before_update hook rejected the request",
				"content":     oaJSONContent(oaSchemaRef("ValidationErrorResponse")),
			},
		},
	}
}

// addOAAuthSchemas registers the request/response component schemas for the
// auth-as-product endpoints and the file store, so the served spec documents their
// exact JSON shapes (matching pkg/userauth and pkg/files).
func addOAAuthSchemas(schemas map[string]any) {
	str := map[string]any{"type": "string"}
	schemas["AuthCredentials"] = map[string]any{
		"type": "object", "required": []string{"email", "password"},
		"properties": map[string]any{
			"email":    map[string]any{"type": "string", "format": "email"},
			"password": str,
		},
	}
	schemas["PublicUser"] = map[string]any{
		"type": "object",
		"properties": map[string]any{
			"id":             map[string]any{"type": "string", "format": "uuid"},
			"email":          map[string]any{"type": "string", "format": "email"},
			"role":           str,
			"email_verified": map[string]any{"type": "boolean"},
			"created_at":     map[string]any{"type": "string", "format": "date-time"},
		},
	}
	schemas["AuthResult"] = map[string]any{
		"type":        "object",
		"description": "Either {user, token} on success, or {mfa_required, mfa_token} when the user has TOTP MFA enabled.",
		"properties": map[string]any{
			"user":         oaSchemaRef("PublicUser"),
			"token":        map[string]any{"type": "string", "description": "the engine JWT (HS256) — send as Authorization: Bearer"},
			"mfa_required": map[string]any{"type": "boolean"},
			"mfa_token":    map[string]any{"type": "string", "description": "short-lived challenge token; complete login at /auth/mfa/verify"},
		},
	}
	schemas["RefreshRequest"] = map[string]any{
		"type": "object",
		"properties": map[string]any{
			"token": map[string]any{"type": "string", "description": "optional — omit to send the token in the Authorization header instead"},
		},
	}
	schemas["TokenResponse"] = map[string]any{
		"type": "object", "required": []string{"token"},
		"properties": map[string]any{"token": str},
	}
	schemas["EmailRequest"] = map[string]any{
		"type": "object", "required": []string{"email"},
		"properties": map[string]any{"email": map[string]any{"type": "string", "format": "email"}},
	}
	schemas["ResetConfirmRequest"] = map[string]any{
		"type": "object", "required": []string{"token", "new_password"},
		"properties": map[string]any{"token": str, "new_password": str},
	}
	schemas["TokenRequest"] = map[string]any{
		"type":       "object",
		"properties": map[string]any{"token": str},
	}
	schemas["MFAVerifyRequest"] = map[string]any{
		"type": "object", "required": []string{"mfa_token", "code"},
		"properties": map[string]any{
			"mfa_token": str,
			"code":      map[string]any{"type": "string", "description": "a current TOTP code or a one-time backup code"},
		},
	}
	schemas["MessageResponse"] = map[string]any{
		"type":       "object",
		"properties": map[string]any{"message": str},
	}
	schemas["FileUploadResult"] = map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_id": map[string]any{"type": "string", "format": "uuid"},
			"sha256":  str,
			"size":    map[string]any{"type": "integer", "format": "int64"},
		},
	}
}

func oaResourceSchema(res *schema.ResourceSchema, includeAuto bool) map[string]any {
	props := map[string]any{}
	if includeAuto {
		props["id"] = map[string]any{"type": "string", "format": "uuid", "readOnly": true}
	}
	var required []string

	for _, fname := range sortedFieldKeys(res) {
		fd := res.Fields[fname]
		if fd.Auto.Enabled() && !includeAuto {
			continue
		}
		props[fname] = oaPropertySchema(fname, fd)
		if fd.Required && !fd.Auto.Enabled() {
			required = append(required, fname)
		}
	}

	out := map[string]any{
		"type":       "object",
		"properties": props,
	}
	if len(required) > 0 {
		sort.Strings(required)
		out["required"] = required
	}
	// Import declaration (WRITE-ASYMMETRY-S1): the resource accepts these
	// governed fields on CREATE from import-granted roles — published so a
	// generic tool can discover the capability from the contract instead of
	// probing. The granted ROLE LIST is deliberately not published: the spec
	// is unauthenticated and role names are not (the ENG-27 anti-enumeration
	// asymmetry). The governed properties keep readOnly:true — that is the
	// truth for every caller outside the grant.
	if res.Import != nil {
		out["x-appximo-import"] = map[string]any{"fields": res.ImportDeclaredFields()}
	}
	return out
}

// oaPropertySchema is oaFieldType plus the x-appximo-* vendor extensions a
// GENERIC tool needs to drive a UI/client from the contract alone
// (FIELD-FEEDBACK-S1, FE5 + PATRON-BACKOFFICE §6). It is used for COMPONENT
// property schemas only — filter query parameters keep the plain oaFieldType,
// where these keys would be noise. The extensions:
//
//   - x-appximo-relation:   the FK's target resource (fd.Relation)
//   - x-appximo-references: the FK's target COLUMN — "id" unless the schema
//     declared otherwise. THE blind spot of FE5: the $user_id pattern the
//     framework itself recommends requires FKs referencing user_id, and a
//     generic relation selector that always sends the row's id violates
//     exactly those FKs; before this key every tool needed a hand-written
//     exception map.
//   - x-appximo-file (+ x-appximo-accept / x-appximo-max-bytes): a file field
//     was indistinguishable from any other uuid FK; the marks let a tool
//     generate the upload→attach widget with the declared policy.
//   - x-appximo-initial / x-appximo-transitions: the state machine, so a UI
//     offers only legal moves (a terminal state is present with an empty
//     list). frontend-spec used to say these were "not in the OpenAPI" —
//     they are now.
func oaPropertySchema(fname string, fd schema.FieldDef) map[string]any {
	m := oaFieldType(fd)
	// Engine-managed timestamps (SILENT-CORRUPTION-S1): the standard readOnly
	// keyword (they appear in responses, never in request bodies — before this
	// only `id` carried it) plus x-appximo-auto naming the EFFECTIVE role —
	// "update" when the engine refreshes the column on every update, "create"
	// when it is set once at insert. A generic tool (the /app back-office, a
	// form generator) reads the truth from the contract instead of guessing it
	// from the two English field names.
	if fd.Auto.Enabled() {
		m["readOnly"] = true
		m["x-appximo-auto"] = fd.EffectiveAutoRole(fname)
	}
	// The declared create-default, as the STANDARD OpenAPI keyword (ENG-38).
	// It tells a generic tool (the /app back-office, a form generator) that a
	// `required` field with a default is satisfiable by OMISSION — without it,
	// every such tool over-demands a value the engine would have filled.
	if fd.Default != nil {
		m["default"] = fd.Default
	}
	if fd.Relation != "" {
		m["x-appximo-relation"] = fd.Relation
		ref := fd.References
		if ref == "" {
			ref = "id" // the schema-level default, made explicit for tools
		}
		m["x-appximo-references"] = ref
	}
	if fd.Type == "file" {
		m["x-appximo-file"] = true
		if len(fd.Accept) > 0 {
			m["x-appximo-accept"] = []string(fd.Accept)
		}
		if fd.MaxBytes > 0 {
			m["x-appximo-max-bytes"] = fd.MaxBytes
		}
	}
	if sm := fd.StateMachine; sm != nil {
		known := sm.KnownStates()
		states := make([]string, 0, len(known))
		for st := range known {
			states = append(states, st)
		}
		sort.Strings(states)
		trans := make(map[string][]string, len(states))
		for _, st := range states {
			if outs := sm.Transitions[st]; len(outs) > 0 {
				trans[st] = outs
			} else {
				trans[st] = []string{} // terminal: present, no exits
			}
		}
		m["x-appximo-initial"] = []string(sm.Initial)
		m["x-appximo-transitions"] = trans
	}
	return m
}

// oaFieldType maps a FieldDef to an OpenAPI type schema object, including the
// declarative validation rules (S44): pattern, min/maxLength, minimum/maximum
// and format translate to their exact OpenAPI equivalents.
func oaFieldType(fd schema.FieldDef) map[string]any {
	switch fd.Type {
	case "string", "text":
		m := map[string]any{"type": "string"}
		if len(fd.Enum) > 0 {
			m["enum"] = fd.Enum
		}
		if fd.MinLength != nil {
			m["minLength"] = *fd.MinLength
		}
		if fd.MaxLength != nil {
			m["maxLength"] = *fd.MaxLength
		}
		if fd.Pattern != "" {
			m["pattern"] = fd.Pattern
		}
		switch fd.Format {
		case "email":
			m["format"] = "email"
		case "uuid":
			m["format"] = "uuid"
		case "url":
			m["format"] = "uri" // OpenAPI's registered name for URLs
		case "date":
			m["format"] = "date"
		}
		return m
	case "int":
		return oaNumericBounds(map[string]any{"type": "integer", "format": "int32"}, fd)
	case "int64":
		return oaNumericBounds(map[string]any{"type": "integer", "format": "int64"}, fd)
	case "float64":
		return oaNumericBounds(map[string]any{"type": "number", "format": "double"}, fd)
	case "bool":
		return map[string]any{"type": "boolean"}
	case "uuid":
		return map[string]any{"type": "string", "format": "uuid"}
	case "file":
		return map[string]any{"type": "string", "format": "uuid",
			"description": "id of an uploaded file (POST /api/files) attached to this record"}
	case "time":
		return map[string]any{"type": "string", "format": "date-time"}
	case "jsonb":
		// An arbitrary JSON document (a real jsonb column): no fixed shape, and
		// clients send/receive the document itself, not a serialized string.
		return map[string]any{
			"description":    "an arbitrary JSON document (jsonb column)",
			"x-appximo-json": "jsonb",
		}
	case "json":
		// ADR-028: the same document contract as jsonb — clients send and
		// receive the VALUE (object, array, number, boolean; a string is read
		// as JSON text). It used to be published as `"type": "string"`, which
		// made every generic form render a text input (and the value, once
		// native, print as `[object Object]`). The tag tells a generic tool
		// which storage it is (TEXT: not queryable, `eq` over canonical text).
		return map[string]any{
			"description":    "an arbitrary JSON document (json column, stored as canonical JSON text)",
			"x-appximo-json": "text",
		}
	default:
		return map[string]any{"type": "string"}
	}
}

// oaNumericBounds copies the min/max validation rules onto a numeric OpenAPI
// schema as minimum/maximum.
func oaNumericBounds(m map[string]any, fd schema.FieldDef) map[string]any {
	if fd.Min != nil {
		m["minimum"] = *fd.Min
	}
	if fd.Max != nil {
		m["maximum"] = *fd.Max
	}
	return m
}

func oaSortEnum(res *schema.ResourceSchema) []string {
	enum := []string{"id"}
	enum = append(enum, sortedFieldKeys(res)...)
	return enum
}

func oaOpsForType(fieldType string) []string {
	switch fieldType {
	case "string", "text":
		return []string{"eq", "partial"}
	case "int", "int64", "float64":
		return []string{"eq", "gt", "gte", "lt", "lte"}
	case "time":
		return []string{"eq", "after", "before", "gte", "lte"}
	default:
		return []string{"eq"}
	}
}

func oaFilterDesc(field, fieldType string) string {
	ops := oaOpsForType(fieldType)
	return "Filter by " + field + ". Operators: " + strings.Join(ops, ", ")
}

func oaOpDesc(field, op string) string {
	switch op {
	case "partial":
		return "Filter " + field + " using ILIKE (case-insensitive substring match)"
	case "gte":
		return "Filter " + field + " ≥ value"
	case "lte":
		return "Filter " + field + " ≤ value"
	case "gt":
		return "Filter " + field + " > value"
	case "lt":
		return "Filter " + field + " < value"
	case "after":
		return "Filter " + field + " strictly after the given date-time"
	case "before":
		return "Filter " + field + " strictly before the given date-time"
	default:
		return "Filter " + field + " by exact value"
	}
}

// ── helpers ──────────────────────────────────────────────────────────────────

func oaSchemaRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/schemas/" + name}
}

func oaRespRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/responses/" + name}
}

func oaJSONContent(s map[string]any) map[string]any {
	return map[string]any{"application/json": map[string]any{"schema": s}}
}

func oaSuccessResp(s map[string]any) map[string]any {
	return map[string]any{"description": "Success", "content": oaJSONContent(s)}
}

func oaErrResp(desc string) map[string]any {
	return map[string]any{"description": desc, "content": oaJSONContent(oaSchemaRef("ErrorResponse"))}
}

func oaQueryParam(name string, s map[string]any) map[string]any {
	return map[string]any{"name": name, "in": "query", "schema": s}
}

func oaQueryParamDesc(name string, s map[string]any, desc string) map[string]any {
	return map[string]any{"name": name, "in": "query", "description": desc, "schema": s}
}

func oaPathIDParam() map[string]any {
	return map[string]any{
		"name":     "id",
		"in":       "path",
		"required": true,
		"schema":   map[string]any{"type": "string", "format": "uuid"},
	}
}

func sortedResourceKeys(s *schema.APISchema) []string {
	keys := make([]string, 0, len(s.Resources))
	for k := range s.Resources {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedFieldKeys(res *schema.ResourceSchema) []string {
	keys := make([]string, 0, len(res.Fields))
	for k := range res.Fields {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
