// Resource: dispatches
// Generated by appitools generate — do not edit manually

package handlers

import (
	"encoding/json"
	"net/http"
)

func ListDispatches(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("[]"))
}

func CreateDispatches(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	var body map[string]any
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(body)
}

func GetDispatchesByID(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"id": "placeholder"})
}

func DeleteDispatches(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNoContent)
}
