// Resource: dispatches
// Generated by appximo generate — do not edit manually

package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	pkghandlers "github.com/appximo/appximo/pkg/handlers"
	querypkg "github.com/appximo/appximo/pkg/query"
	"github.com/appximo/appximo/pkg/rbac"
	"github.com/appximo/appximo/pkg/tenant"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
)

func (h *Handlers) ListDispatches(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	evalResult := rbac.EvalResultFromCtx(r.Context())

	var cond *rbac.WhereCondition
	if evalResult != nil {
		cond = evalResult.Condition
	}

	res := h.apiSchema.Resources["dispatches"]
	qb, err := querypkg.BuildQuery("dispatches", &res, r.URL.Query(), cond, nil)
	if err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}

	selectQ, countQ, selectArgs, countArgs := qb.SQL()

	total, err := h.tdb.QueryScalarTenant(r.Context(), tc.PGSchema, countQ, countArgs...)
	if err != nil {
		writeDBError(w, err)
		return
	}

	rows, err := h.tdb.QueryTenant(r.Context(), tc.PGSchema, selectQ, selectArgs...)
	if err != nil {
		writeDBError(w, err)
		return
	}
	defer rows.Close()
	data, err := pkghandlers.RowsToMaps(rows)
	if err != nil {
		writeDBError(w, err)
		return
	}
	if evalResult != nil && len(evalResult.AllowedFields) > 0 {
		for i, rec := range data {
			data[i] = pkghandlers.FilterFields(rec, evalResult.AllowedFields)
		}
	}
	if data == nil {
		data = []map[string]any{}
	}

	totalPages := (total + int64(qb.PerPage()) - 1) / int64(qb.PerPage())
	if totalPages == 0 {
		totalPages = 1
	}
	hasNext := total > int64(qb.Page()*qb.PerPage())
	hasPrev := qb.Page() > 1

	base := "/api/dispatches"
	buildLink := func(p int) string {
		v := url.Values{}
		v.Set("page", strconv.Itoa(p))
		v.Set("per_page", strconv.Itoa(qb.PerPage()))
		return base + "?" + v.Encode()
	}
	links := map[string]any{
		"self":  buildLink(qb.Page()),
		"first": buildLink(1),
		"last":  buildLink(int(totalPages)),
	}
	if hasPrev {
		links["prev"] = buildLink(qb.Page() - 1)
	}
	if hasNext {
		links["next"] = buildLink(qb.Page() + 1)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"data": data,
		"meta": map[string]any{
			"page":        qb.Page(),
			"per_page":    qb.PerPage(),
			"total":       total,
			"total_pages": totalPages,
			"has_next":    hasNext,
			"has_prev":    hasPrev,
		},
		"links": links,
	})
}

func (h *Handlers) CreateDispatches(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	var body map[string]any
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if len(body) == 0 {
		http.Error(w, "empty body", http.StatusBadRequest)
		return
	}
	hookRes, hookErr := h.hr.RunBeforeHook(r.Context(), h.hookConfig("dispatches", "before_create"), body, nil)
	if hookErr != nil {
		http.Error(w, hookErr.Error(), http.StatusInternalServerError)
		return
	}
	if !hookRes.Proceed {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnprocessableEntity)
		json.NewEncoder(w).Encode(map[string]string{"error": hookRes.Error})
		return
	}
	body = hookRes.Data
	cols, placeholders, args := pkghandlers.BuildInsertArgs(body)
	query := fmt.Sprintf("INSERT INTO dispatches (%s) VALUES (%s) RETURNING *", cols, placeholders)
	result, err := h.tdb.ExecRowsTenant(r.Context(), tc.PGSchema, query, args...)
	if err != nil {
		writeDBError(w, err)
		return
	}
	if afterHook := h.hookConfig("dispatches", "after_create"); afterHook != nil {
		var record map[string]any
		if len(result) > 0 {
			record = result[0]
		}
		go h.hr.RunAfterHook(context.Background(), afterHook, "after_create", record, tc.ID)
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if len(result) > 0 {
		json.NewEncoder(w).Encode(result[0])
	}
}

func (h *Handlers) GetDispatchesByID(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	idStr := chi.URLParam(r, "id")
	if _, err := uuid.Parse(idStr); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid id format"})
		return
	}
	rows, err := h.tdb.QueryTenant(r.Context(), tc.PGSchema, "SELECT * FROM dispatches WHERE id = $1", idStr)
	if err != nil {
		writeDBError(w, err)
		return
	}
	defer rows.Close()
	result, err := pkghandlers.RowsToMaps(rows)
	if err != nil {
		writeDBError(w, err)
		return
	}
	if len(result) == 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "not found"})
		return
	}
	record := result[0]
	evalResult := rbac.EvalResultFromCtx(r.Context())
	if evalResult != nil && len(evalResult.AllowedFields) > 0 {
		record = pkghandlers.FilterFields(record, evalResult.AllowedFields)
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(record)
}

func (h *Handlers) DeleteDispatches(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	idStr := chi.URLParam(r, "id")
	if _, err := uuid.Parse(idStr); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid id format"})
		return
	}
	affected, err := h.tdb.ExecTenant(r.Context(), tc.PGSchema, "DELETE FROM dispatches WHERE id = $1", idStr)
	if err != nil {
		writeDBError(w, err)
		return
	}
	if affected == 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "not found"})
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *Handlers) GetDispatchesGuide(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	idStr := chi.URLParam(r, "id")
	if _, err := uuid.Parse(idStr); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid id format"})
		return
	}
	rows, err := h.tdb.QueryTenant(r.Context(), tc.PGSchema,
		"SELECT r.* FROM guides r JOIN dispatches src ON src.guide_id = r.id WHERE src.id = $1",
		idStr)
	if err != nil {
		writeDBError(w, err)
		return
	}
	defer rows.Close()
	result, err := pkghandlers.RowsToMaps(rows)
	if err != nil {
		writeDBError(w, err)
		return
	}
	if len(result) == 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "not found"})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result[0])
}

func (h *Handlers) GetDispatchesOperator(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	idStr := chi.URLParam(r, "id")
	if _, err := uuid.Parse(idStr); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid id format"})
		return
	}
	rows, err := h.tdb.QueryTenant(r.Context(), tc.PGSchema,
		"SELECT r.* FROM users r JOIN dispatches src ON src.operator_id = r.id WHERE src.id = $1",
		idStr)
	if err != nil {
		writeDBError(w, err)
		return
	}
	defer rows.Close()
	result, err := pkghandlers.RowsToMaps(rows)
	if err != nil {
		writeDBError(w, err)
		return
	}
	if len(result) == 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "not found"})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result[0])
}

// ensure unused imports don't cause compile errors in resources with no relations
var _ = strings.TrimSuffix
