// Resource: guides
// Generated by appitools generate — do not edit manually

package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	pkghandlers "github.com/miguelangel/appitools/pkg/handlers"
	"github.com/miguelangel/appitools/pkg/tenant"
)

func (h *Handlers) ListGuides(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	rows, err := h.tdb.QueryTenant(r.Context(), tc.PGSchema, "SELECT * FROM guides ORDER BY id LIMIT 100")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer rows.Close()
	result, err := pkghandlers.RowsToMaps(rows)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *Handlers) CreateGuides(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	var body map[string]any
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if len(body) == 0 {
		http.Error(w, "empty body", http.StatusBadRequest)
		return
	}
	hookRes, hookErr := h.hr.RunBeforeHook(r.Context(), h.hookConfig("guides", "before_create"), body, nil)
	if hookErr != nil {
		http.Error(w, hookErr.Error(), http.StatusInternalServerError)
		return
	}
	if !hookRes.Proceed {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnprocessableEntity)
		json.NewEncoder(w).Encode(map[string]string{"error": hookRes.Error})
		return
	}
	body = hookRes.Data
	cols, placeholders, args := pkghandlers.BuildInsertArgs(body)
	query := fmt.Sprintf("INSERT INTO guides (%s) VALUES (%s) RETURNING *", cols, placeholders)
	result, err := h.tdb.ExecRowsTenant(r.Context(), tc.PGSchema, query, args...)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if afterHook := h.hookConfig("guides", "after_create"); afterHook != nil {
		var record map[string]any
		if len(result) > 0 {
			record = result[0]
		}
		go h.hr.RunAfterHook(context.Background(), afterHook, record, tc.ID)
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if len(result) > 0 {
		json.NewEncoder(w).Encode(result[0])
	}
}

func (h *Handlers) GetGuidesByID(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	idStr := chi.URLParam(r, "id")
	if _, err := uuid.Parse(idStr); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid id format"})
		return
	}
	rows, err := h.tdb.QueryTenant(r.Context(), tc.PGSchema, "SELECT * FROM guides WHERE id = $1", idStr)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer rows.Close()
	result, err := pkghandlers.RowsToMaps(rows)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if len(result) == 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "not found"})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result[0])
}

func (h *Handlers) DeleteGuides(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	idStr := chi.URLParam(r, "id")
	if _, err := uuid.Parse(idStr); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid id format"})
		return
	}
	affected, err := h.tdb.ExecTenant(r.Context(), tc.PGSchema, "DELETE FROM guides WHERE id = $1", idStr)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if affected == 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "not found"})
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
