// Resource: incidents
// Generated by appitools generate — do not edit manually

package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	pkghandlers "github.com/miguelangel/appitools/pkg/handlers"
	"github.com/miguelangel/appitools/pkg/rbac"
	"github.com/miguelangel/appitools/pkg/tenant"
)

func (h *Handlers) ListIncidents(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	evalResult := rbac.EvalResultFromCtx(r.Context())

	query := "SELECT * FROM incidents ORDER BY id LIMIT 100"
	var queryArgs []any
	if evalResult != nil && evalResult.Condition != nil {
		query = fmt.Sprintf("SELECT * FROM incidents WHERE %s = $1 ORDER BY id LIMIT 100", evalResult.Condition.Field)
		queryArgs = []any{evalResult.Condition.Value}
	}

	rows, err := h.tdb.QueryTenant(r.Context(), tc.PGSchema, query, queryArgs...)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer rows.Close()
	result, err := pkghandlers.RowsToMaps(rows)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if evalResult != nil && len(evalResult.AllowedFields) > 0 {
		for i, rec := range result {
			result[i] = pkghandlers.FilterFields(rec, evalResult.AllowedFields)
		}
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (h *Handlers) CreateIncidents(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	var body map[string]any
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if len(body) == 0 {
		http.Error(w, "empty body", http.StatusBadRequest)
		return
	}
	hookRes, hookErr := h.hr.RunBeforeHook(r.Context(), h.hookConfig("incidents", "before_create"), body, nil)
	if hookErr != nil {
		http.Error(w, hookErr.Error(), http.StatusInternalServerError)
		return
	}
	if !hookRes.Proceed {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnprocessableEntity)
		json.NewEncoder(w).Encode(map[string]string{"error": hookRes.Error})
		return
	}
	body = hookRes.Data
	cols, placeholders, args := pkghandlers.BuildInsertArgs(body)
	query := fmt.Sprintf("INSERT INTO incidents (%s) VALUES (%s) RETURNING *", cols, placeholders)
	result, err := h.tdb.ExecRowsTenant(r.Context(), tc.PGSchema, query, args...)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if afterHook := h.hookConfig("incidents", "after_create"); afterHook != nil {
		var record map[string]any
		if len(result) > 0 {
			record = result[0]
		}
		go h.hr.RunAfterHook(context.Background(), afterHook, record, tc.ID)
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if len(result) > 0 {
		json.NewEncoder(w).Encode(result[0])
	}
}

func (h *Handlers) GetIncidentsByID(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	idStr := chi.URLParam(r, "id")
	if _, err := uuid.Parse(idStr); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid id format"})
		return
	}
	rows, err := h.tdb.QueryTenant(r.Context(), tc.PGSchema, "SELECT * FROM incidents WHERE id = $1", idStr)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer rows.Close()
	result, err := pkghandlers.RowsToMaps(rows)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if len(result) == 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "not found"})
		return
	}
	record := result[0]
	evalResult := rbac.EvalResultFromCtx(r.Context())
	if evalResult != nil && len(evalResult.AllowedFields) > 0 {
		record = pkghandlers.FilterFields(record, evalResult.AllowedFields)
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(record)
}

func (h *Handlers) DeleteIncidents(w http.ResponseWriter, r *http.Request) {
	tc := tenant.MustFromCtx(r.Context())
	idStr := chi.URLParam(r, "id")
	if _, err := uuid.Parse(idStr); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid id format"})
		return
	}
	affected, err := h.tdb.ExecTenant(r.Context(), tc.PGSchema, "DELETE FROM incidents WHERE id = $1", idStr)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if affected == 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "not found"})
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
