// Generated by appitools generate — do not edit manually

package handlers

import "github.com/go-chi/chi/v5"

func RegisterRoutes(r chi.Router) {
	r.Get("/api/clients", ListClients)
	r.Post("/api/clients", CreateClients)
	r.Get("/api/clients/{id}", GetClientsByID)
	r.Delete("/api/clients/{id}", DeleteClients)
	r.Get("/api/dispatches", ListDispatches)
	r.Post("/api/dispatches", CreateDispatches)
	r.Get("/api/dispatches/{id}", GetDispatchesByID)
	r.Delete("/api/dispatches/{id}", DeleteDispatches)
	r.Get("/api/guides", ListGuides)
	r.Post("/api/guides", CreateGuides)
	r.Get("/api/guides/{id}", GetGuidesByID)
	r.Delete("/api/guides/{id}", DeleteGuides)
	r.Get("/api/incidents", ListIncidents)
	r.Post("/api/incidents", CreateIncidents)
	r.Get("/api/incidents/{id}", GetIncidentsByID)
	r.Delete("/api/incidents/{id}", DeleteIncidents)
	r.Get("/api/users", ListUsers)
	r.Post("/api/users", CreateUsers)
	r.Get("/api/users/{id}", GetUsersByID)
	r.Delete("/api/users/{id}", DeleteUsers)
}
