// Generated by appitools generate — do not edit manually

package handlers

import (
	"github.com/go-chi/chi/v5"
	"github.com/miguelangel/appitools/pkg/db"
	"github.com/miguelangel/appitools/pkg/extensions"
	schemapkg "github.com/miguelangel/appitools/pkg/schema"
)

type Handlers struct {
	tdb       *db.TenantDB
	hr        *extensions.HookRunner
	apiSchema *schemapkg.APISchema
}

func NewRouter(tdb *db.TenantDB, hr *extensions.HookRunner, s *schemapkg.APISchema) *chi.Mux {
	r := chi.NewMux()
	h := &Handlers{tdb: tdb, hr: hr, apiSchema: s}
	r.Get("/api/clients", h.ListClients)
	r.Post("/api/clients", h.CreateClients)
	r.Get("/api/clients/{id}", h.GetClientsByID)
	r.Delete("/api/clients/{id}", h.DeleteClients)
	r.Get("/api/dispatches", h.ListDispatches)
	r.Post("/api/dispatches", h.CreateDispatches)
	r.Get("/api/dispatches/{id}", h.GetDispatchesByID)
	r.Delete("/api/dispatches/{id}", h.DeleteDispatches)
	r.Get("/api/guides", h.ListGuides)
	r.Post("/api/guides", h.CreateGuides)
	r.Get("/api/guides/{id}", h.GetGuidesByID)
	r.Delete("/api/guides/{id}", h.DeleteGuides)
	r.Get("/api/incidents", h.ListIncidents)
	r.Post("/api/incidents", h.CreateIncidents)
	r.Get("/api/incidents/{id}", h.GetIncidentsByID)
	r.Delete("/api/incidents/{id}", h.DeleteIncidents)
	r.Get("/api/users", h.ListUsers)
	r.Post("/api/users", h.CreateUsers)
	r.Get("/api/users/{id}", h.GetUsersByID)
	r.Delete("/api/users/{id}", h.DeleteUsers)
	return r
}

// hookConfig looks up a lifecycle hook (e.g. "before_create") for a resource.
// Returns nil when no hook is configured, so callers can pass it directly to HookRunner.
func (h *Handlers) hookConfig(resource, lifecycle string) *schemapkg.HookConfig {
	res, ok := h.apiSchema.Resources[resource]
	if !ok {
		return nil
	}
	hc, ok := res.Hooks[lifecycle]
	if !ok {
		return nil
	}
	c := hc
	return &c
}
